version: "3.8"

services:
    rest:
        build: .
        command: python3 manage.py runserver 0.0.0.0:8000
        volumes: 
            - .:/rest
        ports:
            - 8000:8000

    frontend:
        build: ./frontend
        tty: true
        volumes:
            - ./frontend:/frontend
            - ./frontend:/frontend/node_modules
        ports:
            - "3000:3000"
        depends_on:
            - rest
        command: npm start